### PR TITLE
Firefox and Edge extensions

### PR DESCRIPTION
**Pull request by Scrxtchy**
Could be simplified a bit more but it works :shipit:

### CODE REVIEW

**Comment by njuljsong** [comment]
@Scrxtchy Thanks for your work!

I just read your update briefly, and I have 2 questions.
*  as I understand, with your PR, this extension will work for Firefox and Edge by adding it locally, right?

*  as I am in chrome dev console, `chrome` is an object while `browser` is `undefined`, so I am wondering if the comments on line 82 and line 101 are misplaced. Also, there is duplicated logics since [line 83](https://github.com/njuljsong/wsjUnblock/pull/17/files#diff-08511402ef2db09f41a8a634333ff927R83),  I am wondering if we can do something like this instead.

```
browser = typeof browser !== "undefined" ? browser : chrome;

// add listeners to browser...
```

**Comment by Scrxtchy** [comment]
Oh I wrote the if statement with chrome first initially, but this tricks out Edge for some reason, I must have forgotten to update the comments.

But yes I tested these locally on all browsers and they check out

**Comment by njuljsong** [comment]
@Scrxtchy thanks!

IMHO, the minimum change as I can see is to add this line:

```
browser = typeof browser !== "undefined" ? browser : chrome;
```
and change `chrome` to `browser` in these two lines: `chrome.webRequest.onBeforeRequest.addListener` and `chrome.webRequest.onBeforeSendHeaders.addListener`.

What do you think?

**Comment by njuljsong** [comment]
Hi @Scrxtchy it is a little complicated to merge this PR, so I jus start [another pr](https://github.com/njuljsong/wsjUnblock/pull/25) with your idea. Thanks a lot!

**Pull request closed without merging**
