### PR TITLE
LinkedIn: remove login wall and scroll freeze [CSS-only]

### PR DESCRIPTION
**Pull request by geordgez**
### Description
Similar to PR #3 for `cooking.nytimes.com`, remove the login modal window that pops up as well as the scroll freeze imposed on profiles where public profile contents are fully loaded.

**NOTE:** this is CSS-only and therefore only works if you hit the "soft" login wall where profile content is loaded. If you browse too many unique profiles (around 10-20) and hit the "hard" login wall, this won't help.

CSS adapted/copied over from [this project repo for creating a CSS-only modifier via bookmarklet](https://github.com/geordgez/linkedin-login-wall-css/)

This is a follow-up to PR #23

### CODE REVIEW

**Comment by njuljsong** [comment]
Hi George @geordgez , this is very nice to remove login modal of Linkedin. Thank you!

While I loaded your PR locally and updated the extension in my local chrome, and log out of Linkedin.com,
when I hit `https://www.linkedin.com/in/georgezeng` in the browser, it redirected me to the login page
screen shot 2018-01-28 at 5 18 38 pm

It seems that I did not get it. Would you mind showing me what I did wrong and how it works?

**Comment by geordgez** [comment]
Hi @njuljsong: thanks for letting me know! That's interesting for two reasons:
- The screen you're getting is the "hard" login wall. 
    - Since my PR only addresses CSS, it only removes the modal window and scroll lock when the full public profile contents load and LinkedIn just adds some elements to obscure the page (what I call the "soft" login wall)
    - The "soft" login wall is imposed on the actual profile URL i.e. `*.linkedin.com/in/*` and doesn't redirect you to 
    - The "hard" login wall is when LinkedIn redirects you to a page where none of the profile contents are loaded
    - The "hard" login wall will usually have a URL like `*.linkedin.com/authwall=...`
    - I suspect the "hard" login wall is some kind of JS-based redirect but I haven't dug around enough yet to figure out which script I should be blocking. It also seems that LinkedIn also tracks your IP from the server side to see if you've viewed too many profiles and will automatically redirect you to the "hard" login wall if you've already viewed a bunch of unique profiles in a given amount of time
- I just tried viewing my own profile and other profiles and it worked fine (see screenshots below). I did try to use the add-on with an incognito window in Chrome and it redirected me to the "hard" login wall (`*linkedin.com/authwall=...`). 

Here's an example of the "soft" login wall:

screen shot 2018-01-28 at 5 47 41 pm

When I activate the extension, the resulting window becomes:

screen shot 2018-01-28 at 5 48 10 pm

Let me know if that helps and if the extension is still failing even on "soft" login walls. I wrote about some of the other things you might want to try [in a blog post](https://geordgez.github.io/jots/2017/11/20/linkedin-login-wall) and so you might also need to:
- turn your WiFi off/on
- clear cookies/cache/browsing history
- restart your computer

**Comment by geordgez** [comment]
Question for you @njuljsong: are there any LinkedIn profiles for which you get a "soft" login wall? Or are all profiles sent to the `authwall` URL? 

Here are a couple of suggestions:
- Try viewing [Jeff Weiner's LinkedIn profile](https://www.linkedin.com/in/jeffweiner08) rather than mine since I've recently been hitting mine very often and I sometimes get redirected to the "hard" login wall immediately
- Trying using the extension on a different computer and browsing two unique profiles from the other computer. If you're always getting the "hard" login wall, then your IP is somehow blacklisted to only show the `authwall` "hard" login wall

Your situation is interesting, I'm guessing somehow they've identified that they should always serve you the "hard" login wall. Maybe:
- You have another extension that leads LinkedIn to redirect you after not sensing some other asset being loaded
- LinkedIn has some conditional or situation-specific restrictions for how you're viewing my profile

**Comment by njuljsong** [comment]
I tried `https://www.linkedin.com/in/jeffweiner08` using Firefox just now, still the same "hard" wall. Then I cleaned cookie in my iphone safari and did it again, still hit the "hard" wall.

It seems to me that this is not a deterministic solution.

**Comment by geordgez** [comment]
I'll admit that I don't know how to  deterministically circumvent the "hard" wall. My final suggestion (again, I don't know if this will work) is to try it on another laptop/desktop altogether: recently, I've never been able to view a "soft" login wall on my phone, even after requesting a desktop site in the browser options.

I do know, however, that the "soft" wall is deterministically removed. As I noted in the description, the PR

> is CSS-only and therefore only works if you hit the "soft" login wall where profile content is loaded,

I can verify across Firefox and Chrome that it works every time for the "soft" wall. As I don't know how to give you an opportunity to apply the extension to a "soft' wall, would you want to see some more screenshots of LinkedIn profiles where I'm able to remove the "soft" wall? I can also ask some others to testify that it works for the its purpose of removing the "soft" wall.

**Comment by njuljsong** [comment]
OK. I understand this PR would work if the "soft" wall appears. It bugs me that I am not able to see the "soft" wall in my laptop by cleaning up cookie, using different browser and in different time. I'll try using another computer to see if I can see it.

**Comment by geordgez** [comment]
Sounds good! Sorry that you can't verify it just yet--it would be a lot easier if I had actually figured out how to avoid the "hard" wall via JS 😞   That would be a better approach in the original spirit of your add-on.

**Comment by vnguyen01** [comment]
I just installed [geordgez's version of the extension for LinkedIn](https://github.com/geordgez/wsjUnblock) for Chrome and can verify that it works for the soft login wall

**Comment by njuljsong** [comment]
Hi @geordgez and @vnguyen01 Thanks for your test and help. Sorry for the delay. 

I set up my window machine at home, install this PR in its chrome browser, and try to access [Jeff Weiner's LinkedIn page](https://www.linkedin.com/in/jeffweiner08), still hit the hard paywall(look like `https://www.linkedin.com/authwall?...`).

So I don't have enough evidence that this PR will work universally. I'll just close it for now. If there is any new progress, please reopen it. Thank you very much!

**Comment by geordgez** [comment]
No worries, it looks like LinkedIn removed the soft paywall altogether, at least for my recent tests. I did make a comment about it to one of my friends who works there as a software engineer so I probably shot myself in the foot. I'll make a new PR if I find out how to deal with the hard login wall.

**Pull request closed without merging**
